name: Build TCLI Image

on:
  workflow_dispatch:
    inputs:
      push:
        type: boolean
        description: 'Push the image to the registry'
        default: false
  release: 
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build Docker Image
      run: docker build . --file Dockerfile.tcli --tag ghcr.io/dhkatz/tcli:latest
    - name: Authenticate with GitHub Container Registry
      if: ${{ github.event_name == 'release' || github.event.inputs.push == 'true' }}
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_TOKEN }}
    - name: Push Docker Image
      if: ${{ github.event_name == 'release' || github.event.inputs.push == 'true' }}
      run: docker push ghcr.io/dhkatz/tcli:latest
